CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE job_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies (id),
    role_title VARCHAR(200) NOT NULL,
    status VARCHAR(30) NOT NULL,
    application_date DATE NOT NULL,
    notes VARCHAR(5000) NOT NULL DEFAULT '',
    last_activity_date DATE NOT NULL,
    CONSTRAINT job_applications_status_check CHECK (
        status IN ('APPLIED', 'INTERVIEWING', 'OFFER', 'REJECTED', 'WITHDRAWN')
    )
);

CREATE INDEX job_applications_company_id_index
    ON job_applications (company_id);

CREATE TABLE job_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_application_id BIGINT NOT NULL REFERENCES job_applications (id) ON DELETE CASCADE,
    event_type VARCHAR(50) NOT NULL,
    event_date DATE NOT NULL,
    details VARCHAR(5000),
    CONSTRAINT job_events_event_type_check CHECK (
        event_type IN ('APPLICATION_CREATED', 'STATUS_CHANGED', 'NOTES_UPDATED')
    )
);

CREATE INDEX job_events_job_application_id_index
    ON job_events (job_application_id);
